### ISSUE TITLE
add image under the HeatMap

### ISSUE THREAD

**Issue by ryanleefromtw** [HeartlandSoftware/AndroidHeatMap#1]
hey
firstly, thanks for the great work but i get a question, how can i put an image under the heatMap.
In my case I have a indoor map image and i want to draw the heatmap on it. How can I do this?
thanks!!!

**Comment by tredpath** [comment]
Place an `ImageView` behind the `HeatMap` to display your indoor map image. If you have transparency in the color stops used in the `HeatMap` the `ImageView` will show through.

**Comment by akashspatil** [comment]
Use background property in xml. it worked for me.

**Comment by android-bash** [comment]
> hey
> firstly, thanks for the great work but i get a question, how can i put an image under the heatMap.
> In my case I have a indoor map image and i want to draw the heatmap on it. How can I do this?
> thanks!!!

If you have done it, can you please share your code? I need something similar. Thanks for an help.

**Comment by android-bash** [comment]
> Use background property in xml. it worked for me.

If you have done it, can you please share your code? I need something similar. Thanks for an help.
