### ISSUE TITLE
Display values for each data point

### ISSUE THREAD

**Issue by Amandab-u** [HeartlandSoftware/AndroidHeatMap#10]
Hi, awesome library, it helped me a lot. I was wondering if there is a way to show the value for each point? 
Thank you!

**Comment by tredpath** [comment]
It would be possible to draw something with the value in it using the marker callback. Register a callback using [setMarkerCallback](https://github.com/HeartlandSoftware/AndroidHeatMap/blob/3e97d48d9bd3185c5fd4dae6151c50a076871ebd/HeatMapLib/src/main/java/ca/hss/heatmaplib/HeatMap.java#L232). You will have to manually draw the value on the [Canvas](https://developer.android.com/reference/android/graphics/Canvas) that the callback passes you.

If you instead want to show the value when the user touches the heatmap you can register an [OnMapClickListener](https://github.com/HeartlandSoftware/AndroidHeatMap/blob/3e97d48d9bd3185c5fd4dae6151c50a076871ebd/HeatMapLib/src/main/java/ca/hss/heatmaplib/HeatMap.java#L364) to be notified when the user touches the heatmap and the closest datapoint to where they touched. Then show the value in any kind of popup or toast.

**Comment by Amandab-u** [comment]
Hi! I have a set of points and each of them has different values so I did the second option and it works fine. But, when I tried to do the first option with the setMarkerCallback all the points have the same value (which is the value of the last point it sees), instead of showing all the different values for each point. 

map.setMarkerCallback(new HeatMapMarkerCallback() {
                @Override
                public void drawMarker(Canvas canvas, float v, float v1) {
                    Paint paint = new Paint();
                    paint.setColor(Color.RED);
                    paint.setStyle(Paint.Style.FILL);
                    paint.setTextSize(20);
                    canvas.drawCircle(v,v1,5,paint);
                    canvas.drawText(String.valueOf((int)point1.value), v, v1, paint);
                }
            });
}
To explain a little more I have 9 points with values (0 1 2 3 4 5 6 7 8) and instead of showing this, it shows all the points with the value "8" 
If maybe you know what I'm doing wrong it will be appreciated, I'm pretty new in programming in general and I've learn everything on my own. If not, thank you so much! because the pop-up message with the value helps me anyways for what I'm trying to do.

**Comment by tredpath** [comment]
It looks like you're always drawing whatever value is stored in `point1.value`. I've updated the library to [v1.2.0](https://github.com/HeartlandSoftware/AndroidHeatMap/releases/tag/1.2.0) which now passes you the DataPoint to the drawMarker method. You should then be able to get the value to display from that. I also updated the platform and dependency versions, hopefully that won't cause you issues.

It also looks like you're using the same color for a background circle and the text. This may not be causing you issues yet as a radius of 5px is a really small circle. You should create two separate paints, one for the background and one for the text, and only create them once.

An update to your sample using the updated version:

```java
final Paint backPaint = new Paint();
backPaint.setColor(Color.RED);
backPaint.setStyle(Paint.Style.FILL);

final Paint textPaint = new Paint();
textPaint.setColor(Color.BLACK);
textPaint.setTextSize(20);
textPaint.setStyle(Paint.Style.FILL);

map.setMarkerCallback(new HeatMapMarkerCallback() {
    @Override
    public void drawMarker(Canvas canvas, float x, float y, HeatMap.DataPoint point) {
        canvas.drawCircle(x, y, 5, backPaint);
        canvas.drawText(String.valueOf((int)point.value), x, y, textPaint);
    }
});
```

**Comment by Amandab-u** [comment]
Thank you! It works perfectly. I later realized that I was putting the HeatMapMarkerCallback on a for loop, which always chooses the last value entered on the loop, and that's why it was showing the same value for all the points.
