### ISSUE TITLE
Help with screen coordinates and corresponding areas in the heat map

### ISSUE THREAD

**Issue by pedrobrigatto** [HeartlandSoftware/AndroidHeatMap#2]
Hey guys, great stuff!

I've added the heat map inside a linear layout with a background, which is the area I'd like to cover. I'm capturing the coordinates of the screen, whenever users touch it. In my mind, I'd be able to add point to point in the heat map and it would reflect the temperature accordingly. If I run the example with the random numbers, I can see the picture, the heat displayed, but whenever I try to play with the actual places users have hit, I cannot render it. Is there any way you can give me some tips on how to proceed with it, and the actual meaning of each parameter of this method addData(float, float, double)? In the beginning, I had exceptions when working directly with the values in pixels (getX(), getY() from MotionEvent). Also, I don't have the meaning of this third parameter, 'value', clear.

Thanks in advance, for the great job. Wish you can give me the clarifications to the points above.

**Comment by tredpath** [comment]
The first two parameters of the `DataPoint` constructor are the location of the point as a decimal percentage of the views size. So for x, 0.0 is the very left hand side of the heat map and 1.0 is the very right hand side of the heatmap. The last parameter, value, is the intensity of the data point. If value is equal to the min the color at that point will be the first color in the color stop list (the background color), if it is equal to the max the color at that point will be the last color in the color stop list.

Don't use the raw pixel values from the `MotionEvent`, convert them to a percentage by dividing by `view.getWidth()` or `view.getHeight()`.

**Comment by josinaldobarbosa** [comment]
this tip would be of great help in readme, heatMap.forceRefresh(); after adding date too
